/** 数据和卡片样式的映射关系 */
export enum UIType {
  /** 顶部tab猜你喜欢 */
  TOP_GUESS_YOU_LIKE = 'TOP_GUESS_YOU_LIKE',
  /** 运营banner */
  BANNER = 'BANNER',
  /** 导航入口 */
  NAVIGATION = 'NAVIGATION',
  /** 支持换一换的多图推荐 */
  CHANGEABLE_COMMEND = 'CHANGEABLE_COMMEND',
  /** 猜你喜欢 */
  GUESS_YOU_LIKE = 'GUESS_YOU_LIKE',
  /** 继续阅读 */
  CONTINUE_READ = 'CONTINUE_READ',
  /** 选择阅读喜好 */
  CHOOSE_READ_LIKE = 'CHOOSE_READ_LIKE',
  /** 精彩节选 */
  EXCEPTS = 'EXCEPTS',
  /** 书架卡片 */
  BOOK_SHELF = 'BOOK_SHELF',
  /** 新用户选择阅读喜好 */
  NEW_USER_READ_LIKE = 'NEW_USER_READ_LIKE',
  /** 热门影视原著 */
  FILM_BOOK = 'FILM_BOOK',
  /** 单排行外露卡片 */
  SINGLE_RANK = 'SINGLE_RANK',
  /** 男女生的分类标签 */
  CATEGORY = 'CATEGORY',
  /** 书架tab下书架卡 */
  TAB_BOOK_SHELF = 'TAB_BOOK_SHELF',
  /** 书架tab下推书卡 */
  TAB_CATCH_UP = 'TAB_CATCH_UP',
  /** 多榜单外露卡片 */
  RANK = 'RANK',
  /** kol推书卡片 */
  KOL_BOOK = 'KOL_BOOK',
  /** 视频推书卡片 */
  VIDEO_BOOK = 'VIDEO_BOOK',
  /** 新用户pick主角/技能卡片 */
  SKILL_BOOK = 'SKILL_BOOK',
  /** 多书籍拼接书籍推荐 */
  MORE_COMMEND = 'MORE_COMMEND',
  /** 有声书直播卡片 */
  LIVE_BOOK = 'LIVE_BOOK',
  /** 点击无限流推荐Item返回后，出的推荐卡片 */
  RECOMM_CARD_IN_INFINITY = 'RECOMM_CARD_IN_INFINITY',
  /** 新分类标签（分类导航优化时未定义，后续迁移时使用） */
  CATEGORY_NEW = 'CATEGORY_NEW',
  /** 新分类标签，加推荐内容卡片 */
  CATEGORY_CONTENT_BOOK = 'CATEGORY_CONTENT_BOOK',
  /** 书单卡片 */
  BOOK_LIST = 'BOOK_LIST',
  /** 作者卡片 */
  AUTHOR_LIST = 'AUTHOR_LIST',
  /** 免广告倒计时卡片 */
  NEW_USER_AD_FREE = 'NEW_USER_AD_FREE',
  /** 新浅用户福利卡 */
  NEW_USER_WELFARE = 'NEW_USER_WELFARE',
  /** 见识Tab分类标签 */
  CATEGORY_KNOWLEDGE = 'CATEGORY_KNOWLEDGE',
  /** 全宽大图卡片 */
  FULL_WIDTH_IMAGE = 'FULL_WIDTH_IMAGE',
  /** 话题卡片 */
  TOPIC = 'TOPIC',
}
